### PR TITLE
ignore node_modules after running the app locally

### PR DESCRIPTION
**Pull request by ivanB1975**
If you run the app locally, it creates the node_modules directory. When pushing it to Cloud Foundry also this directory is pushed as well. It would be better to exclude the directory node_modules from the uploaded files. This would decrease the size of the files to upload and avoid possible conflicts generated by the local modules.

### CODE REVIEW

**Comment by ivanB1975** [comment]
@mastertinner  after installing the module locally (npm install) a git push shows a bigger payload and the staging fails because of an incompatibile library. Adding explicitly the node_modules directory to the .cfignore, solved the problem and the payload measures the same as the one without node_modules. Can you try simply to clone the repo. make a npm install and then a cf push and see what happens?

**Comment by ivanB1975** [comment]
@mastertinner ps regarding gitignore here the common practice I found for Node: https://github.com/github/gitignore/blob/master/Node.gitignore
The general * is not used but it appears that everything is explicitly added. I think that is a better practice, but this is just an opinion :)

**Comment by cloudlena** [comment]
@ivanB1975, this commit concerns the `.cfignore` though. Not the `.gitignore`. Right?

**Comment by ivanB1975** [comment]
@mastertinner yes, off course. In some places I saw also "/\*" to exclude all. I raised the merge request when I found that the 
`*

!src/
!package.json
!package-lock.json`

 was not excluding the node modules dir. 
Only explicitly adding the node_modules dir excluded it from being pushed.
I personally think that it looks better the explicit syntax for the cfignore.

**Pull request merged**
